---

- assert:
    that:
      - graph_subscription_callback_url is not none

# https://developers.facebook.com/docs/graph-api/reference/v3.0/app/accounts/test-users#publish
- name: Create a test user
  uri:
    body: |
      {
        "access_token": "{{ graph_access_token }}",
        "permissions": "{{ graph_user_permissions | join(',') }}"
      }
    body_format: json
    headers:
      Accept: application/json
    method: POST
    return_content: yes
    url: https://graph.facebook.com/{{ graph_version }}/{{ ansible_env.FACEBOOK_APP_ID }}/accounts/test-users
  register: response

- set_fact:
    cacheable: yes
    user:
      access_token: "{{ response.json.access_token }}"
      id: "{{ response.json.id }}"
      login_url: "{{ response.json.login_url }}"
  when: response.json is defined

# https://developers.facebook.com/docs/graph-api/reference/user/accounts/#Creating
- name: Create an account for the test user
  uri:
    body: |
      {
        "about": "{{ graph_page_about }}",
        "access_token": "{{ user.access_token }}",
        "category_enum": "{{ graph_page_category_enum }}",
        "cover_photo": {
          "url": "{{ graph_page_cover_photo_url }}"
        },
        "name": "{{ graph_page_name }}",
        "picture": "{{ graph_page_picture }}"
      }
    body_format: json
    headers:
      Accept: application/json
    method: POST
    return_content: yes
    url: https://graph.facebook.com/{{ graph_version }}/{{ user.id }}/accounts

# https://developers.facebook.com/docs/graph-api/reference/v3.0/app/accounts/test-users#read
- name: Retrieve the accounts associated with the test user
  uri:
    headers:
      Accept: application/json
    method: GET
    return_content: yes
    url: https://graph.facebook.com/{{ graph_version }}/me/accounts?access_token={{ user.access_token }}
  register: response

- set_fact:
    page:
      access_token: "{{ response.json.data[0].access_token }}"
      id: "{{ response.json.data[0].id }}"
  when:
    - response.json is defined
    - response.json.data is defined

# https://developers.facebook.com/docs/graph-api/reference/page/subscribed_apps/#Creating
- name: Subscribe the application to real times updates for the test page
  uri:
    body: |
      {
        "access_token": "{{ page.access_token }}"
      }
    body_format: json
    headers:
      Accept: application/json
    method: POST
    return_content: yes
    url: https://graph.facebook.com/{{ graph_version }}/{{ page.id }}/subscribed_apps
  failed_when: not response.json.success
  register: response

# https://developers.facebook.com/docs/graph-api/reference/v3.0/app/subscriptions#publish
- name: Create a webhook subscription for the application
  uri:
    body: |
      {
        "access_token": "{{ graph_access_token }}",
        "callback_url": "{{ graph_subscription_callback_url }}",
        "fields": "{{ graph_subscription_fields | join(',') }}",
        "object": "{{ graph_subscription_object }}",
        "verify_token": "{{ ansible_env.VERIFY_TOKEN }}"
      }
    body_format: json
    headers:
      Accept: application/json
    method: POST
    return_content: yes
    url: https://graph.facebook.com/{{ graph_version }}/{{ ansible_env.FACEBOOK_APP_ID }}/subscriptions
  delay: 10
  register: response
  retries: 10
  until: response.status == 200

# https://developers.facebook.com/docs/facebook-login/access-tokens/
- name: Increase the OAuth token lease
  uri:
    body: |
      {
        "client_id": "{{ ansible_env.FACEBOOK_APP_ID }}",
        "client_secret": "{{ graph_access_token.split('|')[-1] }}",
        "fb_exchange_token": "{{ page.access_token }}",
        "grant_type": "fb_exchange_token"
      }
    body_format: json
    headers:
      Accept: application/json
    method: POST
    return_content: yes
    url: https://graph.facebook.com/{{ graph_version }}/oauth/access_token
  register: response

- set_fact:
    cacheable: yes
    user: "{{ user | combine({'access_token': response.json.access_token}, recursive=True) }}"
  when: response.json is defined

- debug:
    msg: "{{ lookup('template', 'output.j2') }}"

  # Prevent these tasks from running unless explicitly requested.
- name: Destroy the test user
  uri:
    body: |
     {
      "access_token": "{{ graph_access_token }}"
     }
    body_format: json
    headers:
      Accept: application/json
    method: DELETE
    url: https://graph.facebook.com/{{ graph_version }}/{{ user.id }}
  tags:
    - destroy
    - never
